version: "3.8"

services:
  postgres:
    image: postgres:12.22
    container_name: demo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ta_base
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: